{
  fail("Unexpected call to iterator()");
  return null;
}
