{
  RuntimeException exception=new RuntimeException("msg");
  exception.initCause(new RuntimeException("cause"));
  SerializableThrowable serializableThrowable=SerializableThrowable.fromThrowable(exception);
  assertEquals("msg",serializableThrowable.getMessage());
  assertEquals(exception.getStackTrace().length,serializableThrowable.getStackTrace().length);
  assertEquals("java.lang.RuntimeException: msg",serializableThrowable.toString());
  SerializableThrowable cause=(SerializableThrowable)serializableThrowable.getCause();
  assertEquals("cause",cause.getMessage());
  assertEquals("java.lang.RuntimeException: cause",cause.toString());
}
