{
  Double d=Math.random() < 0 ? 42.0 : null;
  try {
    assertEquals(null,d.doubleValue());
    fail("Should have thrown exception");
  }
 catch (  Exception e) {
  }
  try {
    double dd=d;
    fail("Should have thrown exception" + dd);
  }
 catch (  Exception e) {
  }
}
