{
  servletContext.log("Exception while dispatching incoming RPC call",failure);
  try {
    response.setContentType("text/plain");
    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    response.getWriter().write(GENERIC_FAILURE_MSG);
  }
 catch (  IOException ex) {
    servletContext.log("respondWithUnexpectedFailure failed while sending the previous failure to the client",ex);
  }
}
