{
  try {
    throwE("1");
    fail("Should have thrown RuntimeException");
  }
 catch (  RuntimeException e) {
    assertEquals("1",e.getMessage());
    try {
      throwE("2");
      fail("Should have thrown RuntimeException");
    }
 catch (    RuntimeException e2) {
      assertEquals("2",e2.getMessage());
    }
  }
  try {
    throwE("3");
    fail("Should have thrown RuntimeException");
  }
 catch (  RuntimeException e) {
    assertEquals("3",e.getMessage());
  }
}
