{
  try {
    return outer.catchExceptions();
  }
 catch (  Throwable e) {
    return true;
  }
}
