{
  int value=10;
  try {
    assertEquals(0,throwExceptionAndReturn(++value));
    fail();
  }
 catch (  MyException e) {
    assertEquals(11,value);
  }
}
