{
  Object obj1="String";
  assertEquals("msg",obj1,obj1);
  boolean exWasThrown=false;
  try {
    Object obj2="not String";
    assertEquals("msg",obj1,obj2);
  }
 catch (  Throwable ex) {
    exWasThrown=true;
    if (!(ex instanceof AssertionFailedError)) {
      fail("Unexpected type of exception during assertEquals(String,Object,Object) testing");
    }
  }
  if (!exWasThrown) {
    fail("No exception was thrown during assertEquals(String,Object,Object) testing");
  }
}
